### ISSUE TITLE
NER

### ISSUE THREAD

**Issue by loretoparisi** [cisnlp/Glot500#1]
How to reproduce the NER evaluation?

**Comment by kargaranamir** [comment]
Hi. We will complete the missing code part soon.

**Comment by lpq29743** [comment]
Thanks for the attention.

Code for NER, POS, Retrieval, Round-trip alignment uploaded.

**Comment by loretoparisi** [comment]
> Thanks for the attention.
> 
> 
> 
> Code for NER, POS, Retrieval, Round-trip alignment uploaded.

Amazing thank you very much!
