### ISSUE TITLE
Access to Glot500-c

### ISSUE THREAD

**Issue by nikit-srivastava** [cisnlp/Glot500#2]
Hello,

I came across your work through a virtual talk by Prof. Schütze and found it to be a valuable resource. I'm particularly interested in the Glot500-c(Glot500 corpus) data.

At the moment, your README mentions that access to the corpus will be given after filling an online form, and the form will be available soon. Is there any tentative date for the release of the form? The multilingual corpus would greatly assist my research group with our research on language models.

Thank you for maintaining such a helpful repository, your work is greatly appreciated 😊

**Comment by kargaranamir** [comment]
Hi there! Thank you for your interest in our project. Currently, we do not have licenses that permit us to redistribute all the data we have. However, we are working on creating a free version that we can distribute and another version for those who have access to the original data (indirect redistribution).

We are in the final stages of processing the both versions, and while I don't have the exact date, we're getting close to completing the pipeline.

In the meantime, you can still make use of the metadata of the datasets used in this project by visiting the table in link: https://github.com/cisnlp/Glot500#glot500-c. 

Once again, thank you for your patience and support. We'll keep you updated on our progress, and we're excited to share the corpora  with you soon! If you have any further questions or need more information, please feel free to reach out.

**Comment by kargaranamir** [comment]
Hi, thanks for your patience. We provided the part of Glot500-c that we can redistribute here:

https://huggingface.co/datasets/cis-lmu/Glot500

We might make updates, depending on feedback or if further cleaning is performed.
