### ISSUE TITLE
glot500-large

### ISSUE THREAD

**Issue by Bachstelze** [cisnlp/Glot500#3]
Are there plans to train a large glot500 model?
Thanks for your work so far!

**Comment by kargaranamir** [comment]
> Are there plans to train a large glot500 model? Thanks for your work so far!

Hi, thank you for opening this issue. We made some attempts at training, but unfortunately, due to unresolved issues and being GPU poor, the training was not successful. Regrettably, the situation will not change in the foreseeable future.

**Comment by Bachstelze** [comment]
[PEFT](https://github.com/huggingface/peft) could be a solution to lower the hardware consumption and it would be more adaptable. At the moment MLM isn't tested with it:
https://github.com/huggingface/peft/issues/116
Yet there isn't a reason why it shouldn't work.

**Comment by kargaranamir** [comment]
> [PEFT](https://github.com/huggingface/peft) could be a solution to lower the hardware consumption and it would be more adaptable. At the moment MLM isn't tested with it: [huggingface/peft#116](https://github.com/huggingface/peft/issues/116) Yet there isn't a reason why it shouldn't work.

cc @lpq29743 @ayyoobimani
